name: statemint-app
services:
- name: web
  source_dir: /
  github:
    repo: your-username/StateMint-Mock-Frontend
    branch: master
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  build_command: npm run build
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production 